### PR TITLE
Fixes shortcodes (#33) and Wordpress login (#34)

### LINKED ISSUE #33: Shortcode attributes are being ignored
The shortcode attributes are being ignored. In this example, the Lock's title will never be changed, even tough the form_title attributed is defined on the shortcode.

    [auth0 show_as_modal="true" social_big_buttons="true" form_title="Please login on my WP blog"]

Reported here: https://ask.auth0.com/t/shortcode-attributes-go-nowhere-in-auth0-plugin/464

### PR DESCRIPTION
**Pull request by sandrinodimattia**
Fixes #33 and #34

### CODE REVIEW

**Comment by mgonto** [comment]
Hey I'll try this tomorrow :).

What would this fix @sandrinodimattia?

**Comment by sandrinodimattia** [comment]
@mgonto, the issue which was posted here: https://ask.auth0.com/t/shortcode-attributes-go-nowhere-in-auth0-plugin/464. Would it be best to also log an issue here on GH?

**Comment by mgonto** [comment]
Hey I think it'd help for further reference. At least just create the issue and point it to that link and then have the commit do the `Fixes #issueNumber` to have more traceability :). What do you think?

I'll check it up tomorrow!

**Comment by sandrinodimattia** [comment]
Done!

**Comment by sandrinodimattia** [comment]
Added fix for other issue.

**Comment by glena** [comment]
Merged manually for next release

**Pull request closed without merging**
