### PR TITLE
added configurationBaseUrl for allow Cross-Origin Authentication

### PR DESCRIPTION
**Pull request by S0c5**
## Cross-Origin Authentication 
in order to allow the cross origin authentication in SSO, I added the configuration BaseUrl with the url of CDN.

related to issue #386 where the third party cookies cause problems.

### CODE REVIEW

**Comment by cocojoe** [comment]
@joshcanhelp can you review this please, I don't think it should be inserted in this manner.  If this param has value then it should be populated from the Admin panel options.

**Comment by joshcanhelp** [comment]
@S0c5 - I'm not totally clear what this is solving. From the Lock readme:

https://github.com/auth0/lock#other-options

> configurationBaseUrl {String}: Overrides client settings base url. By default it uses Auth0's CDN url when domain has the format *.auth0.com. Otherwise, it uses the provided domain.

Can you help me understand what this would solve? 

Also, as Walsh mentioned, this probably isn't something we want to hardcode as it's possible to change, if needed, right in the wp-admin under **Auth0 > Settings > Advanced > Extra settings**, just drop in an object like:

`{"configurationBaseUrl": "https://cdn.auth0.com"}`

If you `var_dump`/`print_r` right where you made your change and load wp-login.php, you'll see this setting come through:

screenshot 2018-02-01 07 45 40

But, again, that value you're adding is the default.

**Comment by S0c5** [comment]
hi @joshcanhelp  and @cocojoe,

In order to avoid the [limitations-of-cross-origin-authentication](https://auth0.com/docs/cross-origin-authentication#limitations-of-cross-origin-authentication) due the third party cookies, Auth0 recommends implement custom domains because in this way the cookies are no longer third-party and are not blocked by browsers, but when you are using your custom domain the auth0-lock library try to gets the client script by your custom domain and that's raise a error. 

*If you're using Embedded Lock (Lock v11), you need to use your custom domain when initializing Lock. You will also need to set the configurationBaseUrl to the appropriate CDN URL*

the value of **configurationBaseUrl**  can be changed by the region or zone: 

*The CDN URL varies by region. For regions outside of the US, use https://cdn.{region}.auth0.com.*, but by default we can use the base region.

**Comment by joshcanhelp** [comment]
@S0c5 - I guess I'm still confused as to what this PR is trying to achieve. The hard-coded value is the default that's already used and a custom value can be implemented with the settings I described.

**Comment by S0c5** [comment]
Hi @joshcanhelp  I just seen that you are right I can add the parameter by extra settings. Sorry for you time, I Hope contribute some day to this project,!

best regards guys.

**Comment by joshcanhelp** [comment]
No problem, we appreciate the effort!

**Pull request closed without merging**
